FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
RUN npm install
COPY src ./src
RUN npm run build

FROM node:18-alpine AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./package.json
RUN npm install --production
USER node
EXPOSE 3000
CMD ["node", "dist/index.js"]
